/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IdentifyRouteImport } from './routes/identify'
import { Route as ConnectRouteImport } from './routes/connect'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoomsIndexRouteImport } from './routes/rooms/index'
import { Route as RoomsRoomIdIndexRouteImport } from './routes/rooms/$roomId/index'
import { Route as RoomsRoomIdGameRouteImport } from './routes/rooms/$roomId/game'

const IdentifyRoute = IdentifyRouteImport.update({
  id: '/identify',
  path: '/identify',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectRoute = ConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsIndexRoute = RoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdIndexRoute = RoomsRoomIdIndexRouteImport.update({
  id: '/rooms/$roomId/',
  path: '/rooms/$roomId/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoomsRoomIdGameRoute = RoomsRoomIdGameRouteImport.update({
  id: '/rooms/$roomId/game',
  path: '/rooms/$roomId/game',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/identify': typeof IdentifyRoute
  '/rooms': typeof RoomsIndexRoute
  '/rooms/$roomId/game': typeof RoomsRoomIdGameRoute
  '/rooms/$roomId': typeof RoomsRoomIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/identify': typeof IdentifyRoute
  '/rooms': typeof RoomsIndexRoute
  '/rooms/$roomId/game': typeof RoomsRoomIdGameRoute
  '/rooms/$roomId': typeof RoomsRoomIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/connect': typeof ConnectRoute
  '/identify': typeof IdentifyRoute
  '/rooms/': typeof RoomsIndexRoute
  '/rooms/$roomId/game': typeof RoomsRoomIdGameRoute
  '/rooms/$roomId/': typeof RoomsRoomIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/connect'
    | '/identify'
    | '/rooms'
    | '/rooms/$roomId/game'
    | '/rooms/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/connect'
    | '/identify'
    | '/rooms'
    | '/rooms/$roomId/game'
    | '/rooms/$roomId'
  id:
    | '__root__'
    | '/'
    | '/connect'
    | '/identify'
    | '/rooms/'
    | '/rooms/$roomId/game'
    | '/rooms/$roomId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConnectRoute: typeof ConnectRoute
  IdentifyRoute: typeof IdentifyRoute
  RoomsIndexRoute: typeof RoomsIndexRoute
  RoomsRoomIdGameRoute: typeof RoomsRoomIdGameRoute
  RoomsRoomIdIndexRoute: typeof RoomsRoomIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/identify': {
      id: '/identify'
      path: '/identify'
      fullPath: '/identify'
      preLoaderRoute: typeof IdentifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connect': {
      id: '/connect'
      path: '/connect'
      fullPath: '/connect'
      preLoaderRoute: typeof ConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/': {
      id: '/rooms/'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof RoomsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/': {
      id: '/rooms/$roomId/'
      path: '/rooms/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof RoomsRoomIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rooms/$roomId/game': {
      id: '/rooms/$roomId/game'
      path: '/rooms/$roomId/game'
      fullPath: '/rooms/$roomId/game'
      preLoaderRoute: typeof RoomsRoomIdGameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConnectRoute: ConnectRoute,
  IdentifyRoute: IdentifyRoute,
  RoomsIndexRoute: RoomsIndexRoute,
  RoomsRoomIdGameRoute: RoomsRoomIdGameRoute,
  RoomsRoomIdIndexRoute: RoomsRoomIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
